### PR TITLE
For map-matching Docker image, install pgRouting v3.4.0 from source

### PR DESCRIPTION
**Pull request by jarkkoka**
Upgrade to PostgreSQL 14 as well.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-postgres/11)

### CODE REVIEW

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-postgres/11)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`mapmatching/Dockerfile` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-postgres/11#-NDlNFkU88CTfe-IaCdN:-NDlNFkV4QIhNiZUAjT1:blgvqbv) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/a7bc8e12249e90a85c9fd7ad40566d6a756a3a28/mapmatching/Dockerfile#L2)):*
> ```Dockerfile
> # Builder docker image.
> FROM postgis/postgis:14-master
> ```

Upgrading to PostgreSQL 14. Threat or opportunity?



_Code quote:_
```Dockerfile
FROM postgis/postgis:14-master
```

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-postgres/11)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @jarkkoka and @pallost)

___
*[`mapmatching/Dockerfile` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-postgres/11#-NDlNFkU88CTfe-IaCdN:-NDliLqrCE8MC2XJKwfF:b-z1uatq) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/a7bc8e12249e90a85c9fd7ad40566d6a756a3a28/mapmatching/Dockerfile#L2)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Upgrading to PostgreSQL 14. Threat or opportunity?
</blockquote></details>

sure, why not?
___
*[`mapmatching/Dockerfile` line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-postgres/11#-NDlih01BTaAdeKclt0y:-NDlih01BTaAdeKclt0z:bhhrtgg) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/a7bc8e12249e90a85c9fd7ad40566d6a756a3a28/mapmatching/Dockerfile#L22)):*
> ```Dockerfile
>     libboost-graph-dev \
>     libcgal-dev \
>     postgresql-server-dev-${PG_MAJOR} \
> ```

I don't see where this PG_MAJOR variable is set, is it coming from the parent image?
If so, could we mention this around line 4 where the other version env variables are set as well?
___
*[`mapmatching/Dockerfile` line 51 at r1](https://reviewable.io/reviews/hsldevcom/jore4-postgres/11#-NDljPJ6EbF1yVH9LyN9:-NDljPJ6EbF1yVH9LyNA:b-af4pr5) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/a7bc8e12249e90a85c9fd7ad40566d6a756a3a28/mapmatching/Dockerfile#L51)):*
> ```Dockerfile
> 
> # download script for reading docker secrets
> RUN curl -o /tmp/read-secrets.sh "https://raw.githubusercontent.com/HSLdevcom/jore4-tools/main/docker/read-secrets.sh"
> ```

Just an idea: what if we split this into a multi-stage build, for clarity?

```
FROM postgis/postgis:14-master as pgrouting
(do pgrouting install)

FROM pgrouting
(do the rest of the docker image lines)
```

And then could mention in the first stage as a comment that this stage will become obsolete when the https://github.com/pgRouting/docker-pgrouting repository updates to the latest pgrouting version.

Up to you... This current solution is fine too.

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-postgres/11)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @jarkkoka and @pallost)

___
*[`mapmatching/Dockerfile` line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-postgres/11#-NDlih01BTaAdeKclt0y:-NDlnJdE0jePo5pnshav:b34rq22) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/a7bc8e12249e90a85c9fd7ad40566d6a756a3a28/mapmatching/Dockerfile#L22)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't see where this PG_MAJOR variable is set, is it coming from the parent image?
If so, could we mention this around line 4 where the other version env variables are set as well?
</blockquote></details>

Yes, it is coming from the parent image: `FROM postgis/postgis:14-master`. Will add a comment about `PG_MAJOR`.
___
*[`mapmatching/Dockerfile` line 51 at r1](https://reviewable.io/reviews/hsldevcom/jore4-postgres/11#-NDljPJ6EbF1yVH9LyN9:-NDlnikRAU1pYLSOL9xy:b-c6vvr2) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/a7bc8e12249e90a85c9fd7ad40566d6a756a3a28/mapmatching/Dockerfile#L51)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Just an idea: what if we split this into a multi-stage build, for clarity?

```
FROM postgis/postgis:14-master as pgrouting
(do pgrouting install)

FROM pgrouting
(do the rest of the docker image lines)
```

And then could mention in the first stage as a comment that this stage will become obsolete when the https://github.com/pgRouting/docker-pgrouting repository updates to the latest pgrouting version.

Up to you... This current solution is fine too.
</blockquote></details>

Ok. I will test how multi-stage would work.

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-postgres/11)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[`mapmatching/Dockerfile` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-postgres/11#-NDlNFkU88CTfe-IaCdN:-NDlq0iv-D19m1FI-tf3:b-ljm12y) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/a7bc8e12249e90a85c9fd7ad40566d6a756a3a28/mapmatching/Dockerfile#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

sure, why not?
</blockquote></details>

Yes. I guess no problem too.

**Pull request merged**
