### PR TITLE
Add mapmatching database containing data from digiroad

### PR DESCRIPTION
**Pull request by pallost**
The digiroad data is downloaded and imported when the container is started up. The data itself is contained in jore4 azure blob storage

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1)

### CODE REVIEW

**Review by tk-vincit — COMMENTED** [review]
Didn't have time to do complete review, but posting some comments already before next meeting.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-:-MkvAAkrB6C7CpU60OMT:b-sa5t83)* status: 0 of 9 files reviewed, 8 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[docker-compose.yml, line 19 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-Mkv86LWAlGxr6ZQunTv:-Mkv86LWAlGxr6ZQunTw:b-i1fx67) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/docker-compose.yml#L19)):*
> ```YAML
>     environment:
>       - POSTGRES_DB=testdb
>       # - POSTGRES_USER=username
> ```

Forgotten here? Same for the next line.
___
*[README.md, line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-MkvA5Yu7ipqYO0tqt96:-MkvA5Yu7ipqYO0tqt97:b-npkyn6) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/README.md#L27)):*
> ```Markdown
> | ----------------------------- | ------------------ | ------------------------------------------------------------------------------- |
> | SECRET_STORE_BASE_PATH        | /mnt/secrets-store | Directory containing the docker secrets                                         |
> | DIGIROAD_ROUTING_DUMP_VERSION | 2021-09-28         | The version for digiroad routing dump that should be fetched from Azure storage |
> ```

How does user know which values are valid here, or is that self-evident?
___
*[mapmatching/Dockerfile, line 6 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-Mkv9Vr2BqY0xnPPSO72:-Mkv9UMc5A-eHXRrf1wY:b-88s9hw) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/mapmatching/Dockerfile#L6)):*
> ```Dockerfile
> # install curl
> RUN apt-get update && \
>   apt-get install curl -y 
> ```

Trailing spaces
___
*[mapmatching/Dockerfile, line 18 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-Mkv9XW5EeCP9xwQOFCd:-Mkv9XW5EeCP9xwQOFCe:bih5k99) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/mapmatching/Dockerfile#L18)):*
> ```Dockerfile
> HEALTHCHECK --interval=30s --timeout=5s \
>   # have to source the secrets here as well, otherwise the POSTGRES_USER and/or POSTGRES_DB variables might not exist
>   CMD source /tmp/read-secrets.sh && pg_isready -h localhost -U "${POSTGRES_USER}" -d "${POSTGRES_DB}"
> ```

Fancy character
___
*[mapmatching/entrypoint.sh, line 3 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-Mkv8erF9jOsrf1WGpCQ:-Mkv8erF9jOsrf1WGpCR:b-paz5km) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/mapmatching/entrypoint.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> set -eu
> ```

Sometimes we have used to say something like `set -Eeuo pipefail`, should that be the case also here?
___
*[mapmatching/entrypoint.sh, line 18 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-Mkv9AiW3Wf3k64HELqF:-Mkv9AiW3Wf3k64HELqG:b-87o1ev) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/mapmatching/entrypoint.sh#L18)):*
> ```Shell
> echo 'Downloading digiroad routing dump'
> curl -o /docker-entrypoint-initdb.d/02-digiroad_r_routing.sql \
>     https://jore4storage.blob.core.windows.net/jore4-digiroad/digiroad_r_routing_${DIGIROAD_ROUTING_DUMP_VERSION}.sql
> ```

Just thinking if it would make more sense to pass whole url as env variable?

Well, both solutions are fine for me.
___
*[mapmatching/entrypoint.sh, line 22 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-Mkv976a9Woy0yOkIErI:-Mkv976a9Woy0yOkIErJ:b-1v93tv) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/mapmatching/entrypoint.sh#L22)):*
> ```Shell
> # call the original entrypoint to continue execution
> echo 'Start postgres'
> exec /usr/local/bin/docker-entrypoint.sh "$@"
> ```

Fancy looking characters at the end of this line...
___
*[test-secrets/postgres-db, line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-Mkv8Eg3A4B5Y9mi5cgL:-Mkv8Eg3A4B5Y9mi5cgM:b-8hbkfv) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/test-secrets/postgres-db#L1)):*
> ```
> testdb
> ```

Do we have some fancy, broken characters here or is it just reviewable? Same also about the other secrets.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1)* status: 0 of 9 files reviewed, 8 unresolved discussions (waiting on @jarkkoka, @jschummer, @pkainulainen-vincit, and @tk-vincit)

___
*[docker-compose.yml, line 19 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-Mkv86LWAlGxr6ZQunTv:-MlF-7cWACoN5CqQKHo5:b-hfpv0l) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/docker-compose.yml#L19)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Forgotten here? Same for the next line.
</blockquote></details>

removed
___
*[README.md, line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-MkvA5Yu7ipqYO0tqt96:-MlEzksX6hjjFTPbn4m6:bxy5x5s) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/README.md#L27)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

How does user know which values are valid here, or is that self-evident?
</blockquote></details>

IDK, to me it feels self evident :) I extended the description a bit where the dump is downloaded from so with a little logic one can just check that storage account to know what versions are available
___
*[mapmatching/Dockerfile, line 6 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-Mkv9Vr2BqY0xnPPSO72:-MlEzgUj0vcIMSi1Yd74:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/mapmatching/Dockerfile#L6)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Trailing spaces
</blockquote></details>

Done.
___
*[mapmatching/Dockerfile, line 18 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-Mkv9XW5EeCP9xwQOFCd:-MlEzaTADPY8jXEhCXvM:b-3ihy7l) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/mapmatching/Dockerfile#L18)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Fancy character
</blockquote></details>

newline added
___
*[mapmatching/entrypoint.sh, line 3 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-Mkv8erF9jOsrf1WGpCQ:-MlEzSU-1TkRxCmEV26H:b-cg0mhp) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/mapmatching/entrypoint.sh#L3)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Sometimes we have used to say something like `set -Eeuo pipefail`, should that be the case also here?
</blockquote></details>

we don't use pipes here, but I could add if you want...
___
*[mapmatching/entrypoint.sh, line 18 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-Mkv9AiW3Wf3k64HELqF:-MlEyxuICMdtj8ufk3r7:bsdb825) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/mapmatching/entrypoint.sh#L18)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Just thinking if it would make more sense to pass whole url as env variable?

Well, both solutions are fine for me.
</blockquote></details>

It would enforce the client that uses this docker image to know from which url to load the dumps from. It's better to use only version strings
___
*[mapmatching/entrypoint.sh, line 22 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-Mkv976a9Woy0yOkIErI:-MlEyqQNCfhH3xXlRHYa:b-a8c0oh) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/mapmatching/entrypoint.sh#L22)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Fancy looking characters at the end of this line...
</blockquote></details>

added newline
___
*[test-secrets/postgres-db, line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-Mkv8Eg3A4B5Y9mi5cgL:-MlEyhpk0MKCJ6ky8sER:b-prv8gu) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/test-secrets/postgres-db#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Do we have some fancy, broken characters here or is it just reviewable? Same also about the other secrets.
</blockquote></details>

these characters mean that there's no newline at the end of the file. And there should not be any for secrets

**Review by tk-vincit — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-:-MlF5So51JP3cKfnW4CX:bnfp4nl)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, @pkainulainen-vincit, and @tk-vincit)

___
*[README.md, line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-MkvA5Yu7ipqYO0tqt96:-MlF46rqDzLWJj3R6Am3:br0bzsz) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/3f0ad2859372c172ab71b602f53927edff1e524b/README.md#L27)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

IDK, to me it feels self evident :) I extended the description a bit where the dump is downloaded from so with a little logic one can just check that storage account to know what versions are available
</blockquote></details>

Better now.
___
*[README.md, line 29 at r4](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-MlF3g1r1XUqp-ZmPF0L:-MlF3g1r1XUqp-ZmPF0M:brhhd7g) ([raw file](https://github.com/hsldevcom/jore4-postgres/blob/887bfc609370930d214c5f488d5f479d52182d45/README.md#L29)):*
> ```Markdown
> | DIGIROAD_ROUTING_DUMP_VERSION | 2021-09-28         | The version for digiroad routing dump that should be fetched from Azure `jore4storage` |
> 
> All other environment variables are the same as as in `pgrouting/pgrouting`
> ```

Link to pgroutings documentation would ne nice. Didn't find any refenrences to the env variables that it supports in their github page or dockerhub page:
https://github.com/pgRouting/docker-pgrouting#how-to-use
https://hub.docker.com/repository/docker/pgrouting/pgrouting

**Review by tk-vincit — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-postgres/1#-:-MlF7pgk8rf8md6a5j4u:bnfp4nl)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @jarkkoka, @jschummer, and @pkainulainen-vincit)

**Pull request merged**
