### PR TITLE
Initialize stop database for tiamat

### PR DESCRIPTION
**Pull request by culka**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21)* status: all files reviewed, 5 unresolved discussions (waiting on @culka)

___
*[`.github/workflows/cd.yml` line 140 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21#-NSo6AIQ96VBkiatQIVJ:-NSo6AIQ96VBkiatQIVK:bbzj2aq) ([raw file](https://github.com/HSLdevcom/jore4-postgres/blob/c0cc133192157c6840acd3cd5ecb4164793991ed/.github/workflows/cd.yml#L140)):*
> ```YAML
>               hasurausername
>               importerusername
>               tiamat
> ```

I'd like to see consistency here i.e. the same naming pattern repeated as above: `tiamatusername`



_Code quote:_
```YAML
tiamat
```
___
*[`azuredbmock/00-initialize.sql` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21#-NSo6WJ0Ax1kZdMeeFFU:-NSo6WJ0Ax1kZdMeeFFV:bos0myq) ([raw file](https://github.com/HSLdevcom/jore4-postgres/blob/c0cc133192157c6840acd3cd5ecb4164793991ed/azuredbmock/00-initialize.sql#L34)):*
> ```TSQL
> GRANT CREATE ON DATABASE xxx_db_timetables_name_xxx TO xxx_db_hasura_username_xxx;
> 
> -- create database for stop places and give ALL privileges to Tiamat in it
> ```

registry



_Code quote:_
```TSQL
places
```
___
*[`azuredbmock/00-initialize.sql` line 48 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21#-NSo6x8KBEkYefdxqJIz:-NSo6x8KBEkYefdxqJJ-:b-lf8pi7) ([raw file](https://github.com/HSLdevcom/jore4-postgres/blob/c0cc133192157c6840acd3cd5ecb4164793991ed/azuredbmock/00-initialize.sql#L48)):*
> ```TSQL
> CREATE SCHEMA topology;
> ALTER SCHEMA topology OWNER TO xxx_db_tiamat_username_xxx;
> CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
> ```

This is not done for other databases, but the extension still exists in all other databases. IMO this should either (a) be removed or (b) added to all the other databases above?



_Code quote:_
```TSQL
CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
```
___
*[`azuredbmock/00-initialize.sql` line 50 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21#-NSo62DL0B1Cfi0MFUmt:-NSo62DMBY2COHdEULAe:bhnczvr) ([raw file](https://github.com/HSLdevcom/jore4-postgres/blob/c0cc133192157c6840acd3cd5ecb4164793991ed/azuredbmock/00-initialize.sql#L50)):*
> ```TSQL
> CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
> CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;
> CREATE EXTENSION IF NOT EXISTS postgis_topology WITH SCHEMA topology;
> ```

I doubt that this extension would be needed in the Tiamat database. Can it be removed or is it really needed?



_Code quote:_
```TSQL
CREATE EXTENSION IF NOT EXISTS postgis_topology WITH SCHEMA topology;
```
___
*[`test-secrets/db-tiamat-username` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21#-NSo87QK3DDtUPQDi5nO:-NSo87QK3DDtUPQDi5nP:b-mpanzv) ([raw file](https://github.com/HSLdevcom/jore4-postgres/blob/c0cc133192157c6840acd3cd5ecb4164793991ed/test-secrets/db-tiamat-username#L1)):*
> ```
> tiamat
> ```

`tiamatusername` would be in line with all the other usernames, I guess...



_Code quote:_
```
tiamat
```

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @jarkkoka)

___
*[`.github/workflows/cd.yml` line 140 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21#-NSo6AIQ96VBkiatQIVJ:-NSoB-R5ApV7GQuAMET6:bvel4j4) ([raw file](https://github.com/HSLdevcom/jore4-postgres/blob/c0cc133192157c6840acd3cd5ecb4164793991ed/.github/workflows/cd.yml#L140)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I'd like to see consistency here i.e. the same naming pattern repeated as above: `tiamatusername`
</blockquote></details>

Yes, I agree, but unfortunately the username is hardcoded as tiamat in the migration sql files. Unless we want to change it to use a placeholder there
___
*[`azuredbmock/00-initialize.sql` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21#-NSo6WJ0Ax1kZdMeeFFU:-NSoCMiU1wTK2mRMmXCz:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-postgres/blob/c0cc133192157c6840acd3cd5ecb4164793991ed/azuredbmock/00-initialize.sql#L34)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

registry
</blockquote></details>

Done.
___
*[`azuredbmock/00-initialize.sql` line 48 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21#-NSo6x8KBEkYefdxqJIz:-NSoCOyp7wAfjkQ9Yqt0:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-postgres/blob/c0cc133192157c6840acd3cd5ecb4164793991ed/azuredbmock/00-initialize.sql#L48)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This is not done for other databases, but the extension still exists in all other databases. IMO this should either (a) be removed or (b) added to all the other databases above?
</blockquote></details>

Done.
___
*[`azuredbmock/00-initialize.sql` line 50 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21#-NSo62DL0B1Cfi0MFUmt:-NSoEGJLDR7WajHxVylR:bz1zjcj) ([raw file](https://github.com/HSLdevcom/jore4-postgres/blob/c0cc133192157c6840acd3cd5ecb4164793991ed/azuredbmock/00-initialize.sql#L50)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I doubt that this extension would be needed in the Tiamat database. Can it be removed or is it really needed?
</blockquote></details>

There seems to be no use of this in the sql files directly, but there's a lot of java code that uses the database. Topology seems to be used when defining fare zone areas.

When this extension is removed Tiamat seems not to immediately throw any errors related to it.
___
*[`test-secrets/db-tiamat-username` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21#-NSo87QK3DDtUPQDi5nO:-NSoCXVj4wb8It5-yNR6:b-9s723i) ([raw file](https://github.com/HSLdevcom/jore4-postgres/blob/c0cc133192157c6840acd3cd5ecb4164793991ed/test-secrets/db-tiamat-username#L1)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`tiamatusername` would be in line with all the other usernames, I guess...
</blockquote></details>

Same thing as with the workflow cd.yml, Tiamat is currently hardcoded to use `tiamat` username

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21)* status: all files reviewed, 3 unresolved discussions (waiting on @culka)

___
*[`.github/workflows/cd.yml` line 140 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21#-NSo6AIQ96VBkiatQIVJ:-NSolisM-eV8Gs10QfsP:b-qezkjt) ([raw file](https://github.com/HSLdevcom/jore4-postgres/blob/c0cc133192157c6840acd3cd5ecb4164793991ed/.github/workflows/cd.yml#L140)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Yes, I agree, but unfortunately the username is hardcoded as tiamat in the migration sql files. Unless we want to change it to use a placeholder there
</blockquote></details>

Ok, fair enough.
___
*[`test-secrets/db-tiamat-username` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21#-NSo87QK3DDtUPQDi5nO:-NSoR-aO3QDUMWx-G94h:bghq9z8) ([raw file](https://github.com/HSLdevcom/jore4-postgres/blob/c0cc133192157c6840acd3cd5ecb4164793991ed/test-secrets/db-tiamat-username#L1)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Same thing as with the workflow cd.yml, Tiamat is currently hardcoded to use `tiamat` username
</blockquote></details>

Ok, fair enough. Thanks for clearing it up.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21)* status: all files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`azuredbmock/00-initialize.sql` line 49 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21#-NTxXCep0s5HR61S8te8:-NTxXCep0s5HR61S8te9:b-8zyxmb) ([raw file](https://github.com/HSLdevcom/jore4-postgres/blob/2841d0eadca8766a95b523b4e2b8b31c408b70ee/azuredbmock/00-initialize.sql#L49)):*
> ```TSQL
> -- switch database context to stop db to initialize it to the state where tiamat can use it
> \connect xxx_db_tiamat_name_xxx;
> CREATE SCHEMA topology;
> ```

You no longer create the `postgis_topology` extension. If that extension is unnecessary, then this schema can be removed. Or is the extension created as part of Tiamat database migration scripts? If so, then it should be commented here.



_Code quote:_
```TSQL
CREATE SCHEMA topology;
ALTER SCHEMA topology OWNER TO xxx_db_tiamat_username_xxx;
```

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21)* status: all files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

___
*[`azuredbmock/00-initialize.sql` line 49 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21#-NTxXCep0s5HR61S8te8:-NURiyIo2VhD3knw5szq:bcd0omv) ([raw file](https://github.com/HSLdevcom/jore4-postgres/blob/c0367dc925b4c8707f2c875644a4712130c35137/azuredbmock/00-initialize.sql#L49)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You no longer create the `postgis_topology` extension. If that extension is unnecessary, then this schema can be removed. Or is the extension created as part of Tiamat database migration scripts? If so, then it should be commented here.
</blockquote></details>

After some research I think it would be better to keep the topology schema and extension.

**Review by jarkkoka — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21)* status: all files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`azuredbmock/00-initialize.sql` line 53 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-postgres/21#-NUvDv_4-D3bVrIIDfxD:-NUvDv_4-D3bVrIIDfxE:b-dq6hk8) ([raw file](https://github.com/HSLdevcom/jore4-postgres/blob/af845bd49f2587d949880cf58ad2ffba9384ae25/azuredbmock/00-initialize.sql#L53)):*
> ```TSQL
> CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;
> CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;
> CREATE EXTENSION IF NOT EXISTS postgis_topology WITH SCHEMA topology;
> ```

newline character missing from the end. I'd order this `CREATE EXTENSION postgis_topology` more logically right after creating `postgis` extension.

**Pull request merged**
